first = [
	"Audience Recognition",
	"Big Data",
	"Bitcoin",
	"Brand Experience",
	"Brand Score",
	"Brand Story",
	"Brogramming",
	"Chief Uber",
	"Click-Through",
	"Cloud",
	"Collaboration",
	"Connection",
	"Content",
	"Contextual Computing",
	"Convergence",
	"Conversation",
	"Crowdfunding",
	"Cryptocurrency",
	"Culture",
	"Data",
	"Decentralized Information Asset",
	"DevOps",
	"Digital Media",
	"Digital",
	"Emoji",
	"Engagement",
	"Facebook",
	"Functionality",
	"Human Experience",
	"Idea",
	"In-House Social Media",
	"Information",
	"Innovation",
	"Intelligence",
	"Kickstarter",
	"Longform Engagement",
	"Mobile Intimacy",
	"Mobile Platform",
	"Naked",
	"Online Space",
	"Pinterest",
	"Platform",
	"Principal Digital Imaging",
	"Quantification",
	"Reddit",
	"Scalability",
	"Self-Quantification",
	"Senior Information",
	"Shareability",
	"Social Media",
	"Software",
	"Startup",
	"Strategic Partnership",
	"Tablet",
	"Technology",
	"Thought",
	"Tinder",
	"Trend",
	"Tumblr",
	"Twitter",
	"Unique Experience",
	"User Experience",
	"Video Experience",
	"Wearables",
	"Webinar"
]

last = [
	"Advocate",
	"Amplifier",
	"Architect",
	"Agitator",
	"Baron",
	"Commander",
	"Conductor",
	"Connector",
	"Consultant",
	"Curator",
	"Custodian",
	"Directress",
	"Disruptor",
	"Disruptionist",
	"Disruptor", 
	"Evangelist",
	"Fellow",
	"Futurist",
	"Hacker",
	"Gatekeeper",
	"General",
	"Guardian",
	"Guru",
	"Instigator",
	"Lord",
	"Maestro",
	"Mastermind",
	"Maven",
	"Mentor",
	"Messiah",
	"Minister",
	"Mystic",
	"Nerd",
	"Ninja",
	"Officer",
	"Overlord",
	"Philosopher",
	"Prophet",
	"Pioneer",
	"Proctor",
	"Resident",
	"Revisionist",
	"Sage",
	"Savant",
	"Seer",
	"Sentry",
	"Shaman",
	"Shepherd",
	"Sherpa",
	"Steward",
	"Strategist",
	"Sultan",
	"Superintendent",
	"Svengali",
	"Tinkerer",
	"Translator",
	"Tsar",
	"Visionary",
	"Warden",
	"Warlock",
	"Watchman",
	"Wizard"
]

special = [
	"Brogrammer-in-Residence",
	"Conductor of Datafication",  
	"Creator of Things",
	"Crowd-Funder-in-Residence",
	"Curator of Brand Stories",
	"Curator of Datafication",
	"Custodian of Datafication",
	"Custodian of the Quantified Self",
	"Custodian of the Reddit-sphere",
	"Custodian of the Twitterverse",
	"Data-Miner-in-Residence",
	"Digitizer-in-Residence",
	"Disruptor-in-Residence",
	"Early-Adopter-in-Residence",
	"Explainer-in-Residence",
	"Game-Changer-in-Residence",
	"Gamifyer-in-Residence",
	"Geek-in-Residence",
	"Genius-in-Residence",
	"Grand Poobah of Big Data",
	"Grand Poobah of Bitcoin",
	"Grand Poobah of Brand Utilization",
	"Grand Poobah of Cryptocurrencies",
	"Grand Poobah of Digital Innovation",
	"Grand Poobah of Digital Media",
	"Grand Poobah of Disruptive Innovation",
	"Grand Poobah of Functionality",
	"Grand Poobah of Scalability",
	"Grand Poobah of Video Experience",
	"Grand Poobah of Wearables",
	"Grand Poobah of the Online Space",
	"Hacker-in-Chief",
	"Harbinger of Digital Media",
	"Harbinger of Disruptive Innovation",
	"High Preist of Video Experience",
	"High Priest of Bitcoins",
	"High Priest of Brand Utilization",
	"High Priest of Cryptocurrencies",
	"High Priest of Datafication",
	"High Priest of Digital Innovation",
	"High Priest of Functionality",
	"High Priest of Scalability",
	"High Priest of Wearables",
	"High Priest of the Online Space",
	"High Priestess of Data",
	"High Priestess of Digital Media Solutions",
	"High Priestess of Disruptive Innovation",
	"High Priestess of the Quantified Self",
	"In-House Cryptocurrency Wizard",
	"In-House Data Miner",
	"In-House Disruptor",
	"In-House Evangelist",
	"In-House Explainer",
	"In-House Game Changer",
	"In-House Gamifyer",
	"In-House Genius",
	"In-House Pioneer",
	"In-House Tech Evangelist",
	"In-House Tech Mastermind",
	"In-House Tech Maven",
	"In-House Tech Mentor",
	"In-House Tech Mystic",
	"In-House Tech Pioneer",
	"In-House Tech Primo",
	"In-House Tech Sage",
	"In-House Tech Shaman",
	"In-House Tech Sherpa",
	"In-House Tech Sultan",
	"In-House Tech Superintendent",
	"In-House Tech Svengali",
	"In-House Tech Wizard",
	"Influencer-in-Residence",
	"Instagrammer-in-Chief",
	"Instagrammer-in-Residence",
	"Maker of Things",
	"Mastermind-in-Residence",
	"Maven-in-Residence",
	"Mentor-in-Residence",
	"Nerd-in-Residence",
	"Pioneer-in-Residence",
	"Quantified-Self-in-Residence",
	"Resident Agitator",
	"Resident Brogrammer",
	"Resident Digitizer",
	"Resident Disruptionist",
	"Resident Evangelist",
	"Resident Future-Maker",
	"Resident Gamifyer",
	"Resident Influencer",
	"Resident Mastermind",
	"Resident Nerd",
	"Resident Tech Maven",
	"Resident Tech Mentor",
	"Resident Tech Mystic",
	"Resident Tech Pioneer",
	"Resident Tech Primo",
	"Resident Tech Sage",
	"Resident Tech Shaman",
	"Resident Tech Sherpa",
	"Resident Tech Sultan",
	"Resident Tech Svengali",
	"Resident Tech Wizard",
	"Resident Thought Leader",
	"Snapchatter-in-Residence",
	"Tech-Shaman-in-Residence",
	"Tech-Sherpa-in-Residence",
	"Tech-Sultan-in-Residence",
	"Tech-Svengali-in-Residence",
	"Tech-Wizard-in-Residence",
	"Thought-Leader-in-Residence"
]
