app: svjtgbot
service: svjtgbot
tenant: arturtamborski


provider:
  name: aws
  region: eu-west-1

  stage: dev
  runtime: python3.7

  environment:
    TOKEN: ${env:TOKEN}


package:
  include:
    - bot.py
    - deps/**
  exclude:
    - ./**


functions:
  main:
    handler: bot.main

    events:
      - http:
          method: get
          path: ping
          cors: yes
