app: svjtgbot
service: svjtgbot
tenant: arturtamborski


provider:
  name: aws
  region: ${env:AWS_REGION}

  stage: dev
  runtime: python3.7

  environment:
    TG_TOKEN: ${env:TG_TOKEN}


package:
  include:
    - bot.py
    - names.py
  exclude:
    - ./**


functions:
  main:
    handler: bot.main
    events:
      - http:
          path: main
          method: post
          cors: yes
